[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "markitdown-webui-backend"
version = "0.1.0"
description = "FastAPI backend for the MarkItDown web UI"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
keywords = ["markitdown", "fastapi", "markdown", "document-conversion"]
authors = [
  { name = "MarkItDown Maintainers" }
]
dependencies = [
  "fastapi>=0.111.0",
  "uvicorn[standard]>=0.30.0",
  "python-multipart>=0.0.9",
  "pydantic-settings>=2.2.1",
  "markitdown[all]>=0.1.3,<0.2.0",
]

[project.optional-dependencies]
dev = [
  "ruff>=0.5.0",
  "mypy>=1.10.0",
  "pytest>=8.2.0",
  "pytest-asyncio>=0.23.0",
  "httpx>=0.27.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/markitdown_webui_backend"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "ASYNC", "S", "C4", "PIE"]

[tool.mypy]
packages = ["markitdown_webui_backend"]
python_version = "3.10"
strict = false
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
